- name: Destroy previously created Packet.net bare metal device
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install packet.net module dependencies
      pip:
        name: packet-python

    - name: Remove device
      packet_device:
        project_id: "{{ lookup('env', 'PACKET_PROJECT_ID') }}"
        device_ids: "{{ packet_device_id }}"
        state: absent
      register: result
      retries: 5
      delay: 10
      until: result is succeeded
