---
- name:
    Provision the server, install build tools and dependencies
    like Packer, VMware ovftool and Virtualbox.
  hosts: metal
  tasks:
    - name: Run install_dependencies.sh
      script: "{{ playbook_dir }}/bin/install_dependencies.sh"
